### PR TITLE
feat: use the --expect parameter to specify HTTP response code

### LINKED ISSUE #339: Add the expected return API code
For services that need auth, but respond with some code like 403, we could still ping them: `start-test --expect 403 https://acme.com/ping test`

### PR DESCRIPTION
**Pull request by bahmutov**
closes #339

### CODE REVIEW

**Comment by waldemarennsaed** [comment]
This seems like a breaking change to me. Just tried to upgrade from `1.14.0` to `1.15.x` and specifically the step from `1.14.0` to `1.15.0` breaks for me.

I am wondering if anyone else faced this issue.

### Specific issue

In my case, a local test-environment with a vitest web-server & cypress was working fine but the pipeline on GitLab broke because Cypress could not find the application with `1.15.0`. Reverting back to `1.14.0` fixed it for me.

Anyways. Will post more information when I get more insights.

**Comment by MikeMcC399** [comment]
@waldemarennsaed 

I don't see the failure in your logs. Perhaps you are getting something like:

`Error: connect ECONNREFUSED 127.0.0.1:5173`

How are you starting `vite`? 

If you are getting the above error then 

```bash
npx vite --host
```

may get you better results. 

See Vite documentation Server Options [server.host](https://vitejs.dev/config/server-options.html#server-host).

"Specify which IP addresses the server should listen on. Set this to 0.0.0.0 or true to listen on all addresses, including LAN and public addresses.

This can be set via the CLI using --host 0.0.0.0 or --host."

**Comment by waldemarennsaed** [comment]
> @waldemarennsaed
> 
> I don't see the failure in your logs. Perhaps you are getting something like:
> 
> `Error: connect ECONNREFUSED 127.0.0.1:5173`
> 
> How are you starting `vite`?
> 
> If you are getting the above error then
> 
> ```shell
> npx vite --host
> ```
> 
> may get you better results.
> 
> See Vite documentation Server Options [server.host](https://vitejs.dev/config/server-options.html#server-host).
> 
> "Specify which IP addresses the server should listen on. Set this to 0.0.0.0 or true to listen on all addresses, including LAN and public addresses.
> 
> This can be set via the CLI using --host 0.0.0.0 or --host."

Sorry for my late response! But yes, this fixed it. My bad, was too easy ... 😄

**Comment by waldemarennsaed** [comment]
## Update

No, I have not fixed my issue that way (as I wrote in my previous comment). I still had the issue that cypress was suddenly not running correctly in the CI and noticed the following:

### Local setup

In my local setup, I run cypress with an existing `cypress.env.json` file that contains environment variables for our OAUTH provider (authority & client-id) that we then are mocking (to not actually connect to the auth provider).

The mocking just sets a `localStorage` variable, containing the key as `oauth.client:https://my-auth-provider.com;client-id;`. That key contains the mock-values for auth-tokens etc.

Executing the script that we use in the CI (GitLab) locally, works fine. The storage variable is being set correctly.

However, the CI setup & execution is a bit different.

### CI setup

For once, the repository **does not include** the `cypress.env.json`. Instead, _we are passing the environment variables via the CLI command_:

_.gitlab-yml.ci_ file:

```yml
script:
    - npm run ci:test:e2e -- --env oauth_authority=${E2E_OAUTH_AUTHORITY},oauth_client_id=${E2E_OAUTH_CLIENT_ID}
```

while `E2E_OAUTH_AUTHORITY` and `E2E_OAUTH_CLIENT_ID` include the same data as we pass in our local `cypress.env.json` - containing the auth-provider data.

It appears, that this was working _before the upgrade to _`2.0.0` from our previously used version `1.14.0` but after the upgrade, the CLI-commands are not being passed correctly.

The `npm run ci:test:e2e` command executes the following:

```json
{
  "scripts": {
    "ci:test:e2e": "tests/e2e/scripts/start-headless-e2e-tests.sh"
  }
}
```

with the `start-headless-e2e-tests.sh` being:

```sh
#!/bin/bash

# the arguments passed to this script are handed to npm run cypress:headless
npx start-server-and-test preview:e2e http://localhost:7357 \'npm run cypress:headless -- "$@"\'
```

with `npm run cypress:headless` being:

```json
{
  "scripts": {
    "cypress:headless": "cypress run --browser chrome",
  }
}
```

So far so good. But something must have happened between version 1.14.0 and 2.0.0 that the arguments of my `.gitlab-ci.yml` file were not passed down to `cypress run` anymore, so my env-variables **could not been initialized** and my auth-setup was breking - thus, my Cypress E2E tests were failing.

I fixed this by creating a `cypress.env.json` in my CI job which cypress then takes, so finally my issue is fixed.

I still wonder why the arguments could not been passed down anymore, only due to the upgrade of 1.14.0 to 2.0.0.
If there is an answer to this question, I would be very happy. Otherwise, my part is done :) Thanks for the replies!

**Pull request merged**
