### PR TITLE
fix: do not throw if child process no longer exist

### LINKED ISSUE #46: Error: kill ESRCH
## Is this a bug report or a feature request?

Bug report

If this is a bug report, please provide as much info as possible

- version `1.4.1`
- platform: `teamcity`

*expected behavior*

The server to run in CI environment.

*actual behavior*

The command crashes with the following info:

```
[04:09:56][Step 3/6] { Error: kill ESRCH
[04:09:56][Step 3/6]     at exports._errnoException (util.js:1018:11)
[04:09:56][Step 3/6]     at process.kill (internal/process.js:190:13)
[04:09:56][Step 3/6]     at children.forEach.child (/home/teamcity/buildAgent/work/7182f89e35c6b1c9/node_modules/start-server-and-test/src/index.js:32:21)
[04:09:56][Step 3/6]     at Array.forEach (native)
[04:09:56][Step 3/6]     at Promise.fromNode.then.children (/home/teamcity/buildAgent/work/7182f89e35c6b1c9/node_modules/start-server-and-test/src/index.js:31:20)
[04:09:56][Step 3/6]     at tryCatcher (/home/teamcity/buildAgent/work/7182f89e35c6b1c9/node_modules/bluebird/js/release/util.js:16:23)
[04:09:56][Step 3/6]     at Promise._settlePromiseFromHandler (/home/teamcity/buildAgent/work/7182f89e35c6b1c9/node_modules/bluebird/js/release/promise.js:512:31)
[04:09:56][Step 3/6]     at Promise._settlePromise (/home/teamcity/buildAgent/work/7182f89e35c6b1c9/node_modules/bluebird/js/release/promise.js:569:18)
[04:09:56][Step 3/6]     at Promise._settlePromise0 (/home/teamcity/buildAgent/work/7182f89e35c6b1c9/node_modules/bluebird/js/release/promise.js:614:10)
[04:09:56][Step 3/6]     at Promise._settlePromises (/home/teamcity/buildAgent/work/7182f89e35c6b1c9/node_modules/bluebird/js/release/promise.js:693:18)
[04:09:56][Step 3/6]     at Promise._fulfill (/home/teamcity/buildAgent/work/7182f89e35c6b1c9/node_modules/bluebird/js/release/promise.js:638:18)
[04:09:56][Step 3/6]     at /home/teamcity/buildAgent/work/7182f89e35c6b1c9/node_modules/bluebird/js/release/nodeback.js:42:21
[04:09:56][Step 3/6]     at /home/teamcity/buildAgent/work/7182f89e35c6b1c9/node_modules/ps-tree/index.js:86:7
[04:09:56][Step 3/6]     at Stream.a.end (/home/teamcity/buildAgent/work/7182f89e35c6b1c9/node_modules/event-stream/index.js:87:5)
[04:09:56][Step 3/6]     at Stream.onend (internal/streams/legacy.js:44:10)
[04:09:56][Step 3/6]     at emitNone (events.js:91:20) code: 'ESRCH', errno: 'ESRCH', syscall: 'kill' }
[04:09:56][Step 3/6] error An unexpected error occurred: "Command failed.
[04:09:56][Step 3/6] Exit code: 1
[04:09:56][Step 3/6] Command: sh
[04:09:56][Step 3/6] Arguments: -c start-server-and-test start http://localhost:3000 cypress:run:ci
[04:09:56][Step 3/6] Directory: /home/teamcity/buildAgent/work/7182f89e35c6b1c9
[04:09:56][Step 3/6] Output:
[04:09:56][Step 3/6] ".
```

Here are the relevant commands I'm running:

```
"watch-css": "npm run build-css && node-sass-chokidar src/css/scss/ -o src/css/dist/ --watch",
"start": "npm-run-all -p watch-css start-js",
"cypress:run:ci": "./node_modules/.bin/cypress run",
"cypress:ci": "start-server-and-test start http://localhost:3000 cypress:run:ci"
```

`cypress:ci` being the one called in teamcity.

When I run this command locally, it works fine.

Thank you!

### PR DESCRIPTION
**Pull request by mucsi96**
Fixes #46

### CODE REVIEW

**Comment by bahmutov** [comment]
@mucsi96 thank you for submitting this feature, is there are any chance a test could be added, something similar to "demo" scripts?

**Comment by mucsi96** [comment]
Sure. Probably with mocking I can do that. Will add it Today. Also I am wandering do we want to explicitly ignore this error type. Or it’s fine like this?

**Comment by bahmutov** [comment]
Or you could have a serve that immediately exits as soon as it starts and this tool asks it once. 

As far as ignoring - you could just log something to the console or debug message I think

**Comment by mucsi96** [comment]
I tried to come up with test you suggested without too much luck. Unfortunately it's not good if the server just immediately exits as it produces different exception. The child process should run until the `psTree` call and exit immediately after it - which is quite tricky without doing some complex mocking :)

**Comment by mucsi96** [comment]
Do you have any idea how can we write a test for this? Or can we merge this without a test?

**Comment by wlsf82** [comment]
@mucsi96, thanks for the fix. I'm using your fork for now.
Please notify when merging to the original repo so that I can go back to the official one.

**Comment by bahmutov** [comment]
Ok, I will merge the PR, and hope it fixes issue and does not introduce any new ones

**Comment by mucsi96** [comment]
Thx!

**Pull request merged**
