### PR TITLE
Fix pinging the server when it listens on 0.0.0.0 and the user provided the port number

### LINKED ISSUE #333: Node 17 support
## Bug report

Hi, as mentioned in #328 by several people, it seems the package doesn't support node 17+ or at least is unable to execute a command after the server is up and ready. I created a new issue in case it is a different topic than #328 (probably is).

- version: 1.14.0 (latest)
- platform: macOS Monterey 12.2.1
- expected behavior: running `start-server-and-test start 8000 cy:open` should start the app server and open Cypress
- actual behavior: running this ^ starts the server but doesn't open Cypress, hence it eventually times out

### LINKED ISSUE #348: Next.js server start hangs
I created a new next.js project and added start-server-and-test but no matter what I do, the test run doesn't start. This is my output:

```
start-server-and-test http-get://localhost:3000 cypress.run

1: starting server using command "npm run start"
and when url "[ 'http-get://localhost:3000' ]" is responding with HTTP status code NaN
running tests using command "npm run cypress.run"


> rhino-next@0.1.0 start
> next start

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
```

I ran the curl command to check if a Head request returns 200 and it does.

```
curl --head http://localhost:3000/     
HTTP/1.1 200 OK
X-Powered-By: Next.js
ETag: "dz0spzxup038i"
Content-Type: text/html; charset=utf-8
Content-Length: 4199
Vary: Accept-Encoding
Date: Tue, 03 Jan 2023 08:12:49 GMT
Connection: keep-alive
Keep-Alive: timeout=5
```

My guess is the part the says `is responding with HTTP status code NaN` is the problem.

What am I missing here?

Thanks.

### LINKED ISSUE #356: start-server-and-test failure wait for localhost of react-app Node.js 18
This is a follow-on from the issue https://github.com/bahmutov/start-server-and-test/issues/348 "Next.js server start hangs".

## Environment

```text
$ npm ls
react-app-test@0.1.0
├── @testing-library/jest-dom@5.16.5
├── @testing-library/react@13.4.0
├── @testing-library/user-event@13.5.0
├── cypress@12.6.0
├── react-dom@18.2.0
├── react-scripts@5.0.1
├── react@18.2.0
├── start-server-and-test@1.15.4
└── web-vitals@2.1.4
```

Node.js 18.14.x
Windows 11 local
ubuntu-22.04 on GitHub

## Problem description

start-server-and-test fails waiting for http://localhost:3000 locally on Windows 11 with Node.js 18.14.2 and on GitHub in an `ubuntu-22.04` runner using the current default Node.js 18.14.1.

Debug logs show

```text
making HTTP(S) head request to  url:http://localhost:3000 ...
  HTTP(S) error for http://localhost:3000 Error: connect ECONNREFUSED ::1:3000
```

So the IPv6 address ( `::1`) is being tested whilst the server is only listening on the IPv4 address (`127.0.0.1`).

### Windows 11 local

Clone https://github.com/MikeMcC399/react-app-test

```bash
nvm use 18.14.2
npm ci
export DEBUG=start-server-and-test
npm run test:cypress
```

test hangs although the default browser successfully opens http://127.0.0.1:3000.

```text
$ netstat -an | grep LISTENING | grep 3000
  TCP    0.0.0.0:3000           0.0.0.0:0              LISTENING
```

curl receives a reponse for:
`http://localhost:3000`
`http://127.0.0.1:3000`
not for
`http://[::1]:3000`

### GitHub

View workflow log https://github.com/MikeMcC399/react-app-test/actions/workflows/test-react-app.yml or
fork https://github.com/MikeMcC399/react-app-test and run
[.github/workflows/test-react-app.yml](https://github.com/MikeMcC399/react-app-test/blob/master/.github/workflows/test-react-app.yml)

## Workaround

wait for http://127.0.0.1:3000 instead of http://localhost:3000

On Windows 11

```bash
npm run test:cypress:workaround
```

## Related issues

- https://github.com/cypress-io/github-action/issues/802

### PR DESCRIPTION
**Pull request by bahmutov**
Replace assuming the port XXXX refers to `localhost:XXXX` and instead use `127.0.0.1:XXXX`

- closes #356 
- closes #348 
- closes #333

### CODE REVIEW

**Comment by bahmutov** [comment]
@MikeMcC399 what do you think about this solution? I wish I could try pinging both `localhost:XXXX` and `127.0.0.1:XXXX` alternatively but since we rely on wait-on, we cannot do this. I am also thinking this should be a "minor" version bump.

**Comment by MikeMcC399** [comment]
@bahmutov 

- I tried this fix with https://github.com/bahmutov/start-server-and-test/issues/356 and it did not solve the issue. In this issue the `hostname` `localhost` is specified, so it does not rely on `wait-on` assuming a default `hostname`.

- The wait-on issue https://github.com/jeffbski/wait-on/issues/109 is unresolved, although there has been a fork https://github.com/metcoder95/wait-on created where the issue is resolved. The owner of the fork reports that he implemented "Happy Eyeballs" (see https://github.com/metcoder95/wait-on/pull/20).

- I didn't understand your sentence "The latest versions of Node and some web servers listen on host 0.0.0.0 which no longer means localhost." and I am not sure if it is a correct explanation. What I saw in the react-scripts example is that the web server was listening on `0.0.0.0` (meaning all addresses), dns was resolving `localhost` to `127.0.0.1` and `::1` then wait-on tried to test the localhost IPv6 `::1` on Node.js 18 and the web server did not respond.

**Comment by bahmutov** [comment]
Ok so the solution is to use explicit host and maybe put a warning when someone uses just a port Sent from my iPhoneOn Feb 26, 2023, at 12:45, Mike McCready ***@***.***> wrote:﻿
@bahmutov


I tried this fix with #356 and it did not solve the issue. In this issue the hostname localhost is specified, so it does not rely on wait-on assuming a default hostname.


The wait-on issue jeffbski/wait-on#109 is unresolved, although there has been a fork https://github.com/metcoder95/wait-on created where the issue is resolved. The owner of the fork reports that he implemented "Happy Eyeballs" (see metcoder95/wait-on#20).


I didn't understand your sentence "The latest versions of Node and some web servers listen on host 0.0.0.0 which no longer means localhost." and I am not sure if it is a correct explanation. What I saw in the react-scripts example is that the web server was listening on 0.0.0.0 (meaning all addresses), dns was resolving localhost to 127.0.0.1 and ::1 then wait-on tried to test the localhost IPv6 ::1 on Node.js 18 and the web server did not respond.

**Comment by bahmutov** [comment]
Plus why would wait-on matter? We pass full URL to wait-on in this case. Sent from my iPhoneOn Feb 26, 2023, at 12:55, Gleb Bahmutov ***@***.***> wrote:﻿Ok so the solution is to use explicit host and maybe put a warning when someone uses just a port Sent from my iPhoneOn Feb 26, 2023, at 12:45, Mike McCready ***@***.***> wrote:﻿
@bahmutov


I tried this fix with #356 and it did not solve the issue. In this issue the hostname localhost is specified, so it does not rely on wait-on assuming a default hostname.


The wait-on issue jeffbski/wait-on#109 is unresolved, although there has been a fork https://github.com/metcoder95/wait-on created where the issue is resolved. The owner of the fork reports that he implemented "Happy Eyeballs" (see metcoder95/wait-on#20).


I didn't understand your sentence "The latest versions of Node and some web servers listen on host 0.0.0.0 which no longer means localhost." and I am not sure if it is a correct explanation. What I saw in the react-scripts example is that the web server was listening on 0.0.0.0 (meaning all addresses), dns was resolving localhost to 127.0.0.1 and ::1 then wait-on tried to test the localhost IPv6 ::1 on Node.js 18 and the web server did not respond.

**Comment by sodatea** [comment]
FYI I believe this release breaks the Cypress template of `create-vue`:
https://github.com/vuejs/create-vue/actions/runs/4277827772/jobs/7448606700#step:14:22

This looks like a breaking change to me.

I relied on the **documented behavior** that `:4173` resolves to `localhost:4173`, and intentionally removed the host prefix after Vite changed its default from `127.0.0.1` to `localhost`. I expect this to continue working without a major release.

**Comment by sodatea** [comment]
As for the Node.js 17+ and `0.0.0.0` issues, there's an explanation in the Vite documentation:
https://vitejs.dev/config/server-options.html#server-host

In Vite, we choose to default to `localhost` for the least surprise, and warn the users when their configuration might be problematic.

**Comment by MikeMcC399** [comment]
Since this appears to be a breaking change, it would need to be reverted, as breaking changes require the release of a new major version.

**Comment by MikeMcC399** [comment]
@bahmutov 

[How can I revert a release](https://github.com/semantic-release/semantic-release/blob/master/docs/support/FAQ.md#how-can-i-revert-a-release) provides advice about what to do if a release accidently includes a breaking change.

**Comment by sodatea** [comment]
> I deprecated that npm dist tag

`1.x` or `^1.0.0` still resolves to 1.5.5 according to https://semver.npmjs.com/

**Comment by bahmutov** [comment]
Please use the exact dependency versionSent from my iPhoneOn Feb 27, 2023, at 22:54, Haoqun Jiang ***@***.***> wrote:﻿

I deprecated that npm dist tag

1.x or ^1.0.0 still resolves to 1.5.5 according to https://semver.npmjs.com/

**Comment by sodatea** [comment]
> `npm install` disregards the deprecated version 1.5.5.

😮 I didn't know that. Nice feature!
Thank you for pointing this out to me!

**Pull request merged**
