### PR TITLE
feat: Allow passing arguments to test script

### PR DESCRIPTION
**Pull request by tlvince**
This is #103 with a small fix for `npm run demo` et al.

### CODE REVIEW

**Comment by bahmutov** [comment]
so it would be super to merge this, but I would like to see an end-2-end example test (and readme description)

**Comment by tlvince** [comment]
@bahmutov added

**Comment by bahmutov** [comment]
@tlvince take a look at the latest release v1.8.0 - it now allows passing arbitrary shell commands as arguments. I think this makes this PR unnecessary?

```json
{
    "scripts": {
        "start": "npm start",
        "ci": "server-test :8000 'mocha e2e-spec.js --verbose'"
    }
}
```

**Comment by tlvince** [comment]
@bahmutov it's close, but we need to be able pass extra args from the cli, rather than as part of the script itself, e.g.:

```
❯ yarn test:func:ci --spec foo
```

This currently throws on 1.9.0:

```
❯ yarn test:func:ci --spec foo
yarn run v1.15.2
$ start-server-and-test serve:cypress-assets http://localhost:8080 test:func:run --spec foo
/Users/tomvincent/dev/js-modules.verticals/node_modules/lazy-ass/index.js:117
      throw err;
      ^

Error: expected <NPM script name that starts server> <url or port> <NPM script name that runs tests>
example: start-test start 8080 test
see https://github.com/bahmutov/start-server-and-test#use
```

**Comment by bahmutov** [comment]
yup, @tlvince it does not allow you to add test arguments - but with yarn or npx you don't need to! The new syntax allow you to simply do from the terminal:

```
$ yarn start-test serve:cypress-assets 8080 'mocha --spec'
```

See https://github.com/bahmutov/start-server-and-test#npx-and-yarn

I just don't want to add arguments to the _test_ command only, because server start command probably would need the same.

**Comment by tlvince** [comment]
Fair enough. The alternative works fine. Thanks!

**Pull request closed without merging**
