### PR TITLE
fix(deps): update dependency wait-on to v7.2.0

### PR DESCRIPTION
**Pull request by patrick-hardin**
### Release Notes

[v7.2.0](https://github.com/jeffbski/wait-on/releases/tag/v7.2.0)

Update axios from 0.27.2 to latest 1.6.1 which fixes security vulnerability https://github.com/advisories/GHSA-wf5p-g6vw-rhxx.

Thanks @AndrewMax for the PR https://github.com/jeffbski/wait-on/pull/147 and also for those that confirmed it.

### CODE REVIEW

**Review by seanputera — APPROVED** [review]

**Review by mboere-seek — APPROVED** [review]

**Comment by mblumenstingl-n11** [comment]
The overall idea of this pull request is great and I am happy to see it!

The new library (versions) in `package-lock.json` are pointing to a private npm registry at [https://artylab.expedia.biz].
It would be great if you could update that @patrick-hardin or if @bahmutov could confirm that he'll fix this up when merging the PR.

**Comment by patrick-hardin** [comment]
Sorry about that, and thank you for catching it.

**Review by mblumenstingl-n11 — APPROVED** [review]
Thank you!

**Review by mattoddie — APPROVED** [review]

**Review by tbsvttr — APPROVED** [review]

**Comment by tbsvttr** [comment]
Would be nice to see this merged soon. Keep up the good work.

**Review by Jens-n11 — APPROVED** [review]

**Pull request merged**
